# ==========================================
# Database Configuration (PostgreSQL)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexushr}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

# When running locally from Eclipse, set SPRING_DATASOURCE_PASSWORD to your local postgres password
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:80160}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# JWT Configuration (CRITICAL - SET THESE!)
# ==========================================
app.jwt.secret=${APP_JWT_SECRET:ThisIsMyVeryLongSecretKeyForJwt12345678901234567890}
app.jwt.expiration=86400000

# ==========================================
# Logging
# ==========================================
logging.level.root=INFO
logging.level.com.nexushr=DEBUG

#==============================================
# for Mail
#========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=nexushr147@gmail.com
spring.mail.password=fnyytykyouyeqyox

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==========================================
# File Upload Configuration
# ==========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Base Upload Directory
file.upload-dir=uploads/documents

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.operationsSorter=method

springdoc.swagger-ui.tagsSorter=alpha

springdoc.swagger-ui.tryItOutEnabled=true

springdoc.default-produces-media-type=application/json

management.endpoints.web.exposure.include=health

management.endpoint.health.show-details=always